FROM apache/airflow:2.9.3

USER root

RUN apt-get update && apt-get install -y --no-install-recommends sshpass && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow

RUN python -m pip install --no-cache-dir \
    polars \
    python-dotenv \
    minio \
    pyiceberg[s3fs,pyarrow,polars] \
    requests==2.31.0 \
    beautifulsoup4==4.12.2 \
    pandas \
    tls-client==1.0.1 \
    markdownify==1.1.0 \
    regex==2024.4.28  \
    langchain \
    langchain-ollama \
    langchain-chroma \
    discord_webhook
